version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
